#$ -r y                      # Restartable
#$ -ckpt user                # Restart under user; do not change (do not replace with your username)
#$ -V                        # Inherit current environment
#$ -cwd                      # Start job in submission directory
#$ -N Name_BAR           # Job Name
#$ -j y                      # Combine stderr and stdout
#$ -q MS,UI-GPU,CCOM-GPU               # Queue
#$ -l ngpus=1
#$ -pe smp 10              # Request 12 tasks/node, 12 total
#$ -o $JOB_NAME.$JOB_ID.log  # Name of output file
#$ -l h_rt=500:00:00         # Run Time
#$ -S /bin/bash              # Shell to use

module purge
source /Dedicated/schnieders/andthiel/miniconda.sh
conda activate binding_free_energy
hostname
python <BAR.py> --pdb_file <pdb_file>  --forcefield_file <forcefield_file> hp-bcd.xml --traj_i "<traj_i>" --traj_ip1 "<traj_ip1>" --nonbonded_method "PME" --vdw_lambda_i <vdw_lambda_value_i> --elec_lambda_i <elec_lambda_value_i> --vdw_lambda_ip1 <vdw_lambda_value_ip1> --elec_lambda_ip1 <elec_lambda_value_ip1> --alchemical_atoms <alchemical_atoms>
