#$ -r y                      # Restartable
#$ -ckpt user                # Restart under user; do not change (do not replace with your username)
#$ -V                        # Inherit current environment
#$ -cwd                      # Start job in submission directory
#$ -N Name_Equil           # Job Name
#$ -j y                      # Combine stderr and stdout
#$ -q MS,all.q               # Queue
#$ -l ngpus=1
#$ -l gpu_p100=false
#$ -pe smp 10              # Request 12 tasks/node, 12 total
#$ -o $JOB_NAME.$JOB_ID.log  # Name of output file
#$ -l h_rt=500:00:00         # Run Time
#$ -S /bin/bash              # Shell to use

module purge
source /Dedicated/schnieders/andthiel/miniconda.sh
conda activate binding_free_energy
hostname
python <Equil.py> --pdb_file <pdb_file>  --forcefield_file <forcefield_file>  hp-bcd.xml --nonbonded_method "PME" --num_steps 15000000 --step_size 2 --nonbonded_cutoff 1.0

mv output.pdb <pdb_file>
